<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.witchvermillion.seed</groupId>
        <artifactId>seed-feature-participant</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>dev.witchvermillion.seed.participant</groupId>
    <artifactId>seed-feature-participant-runtime</artifactId>

    <dependencies>
        <dependency>
            <groupId>dev.witchvermillion.seed.participant</groupId>
            <artifactId>seed-feature-participant-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.witchvermillion.seed</groupId>
            <artifactId>seed-integration-flecs</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
            <version>8.5.19</version>
        </dependency>
    </dependencies>

</project>