<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.witchvermillion.cardinal.platform.bukkit</groupId>
        <artifactId>cardinal-platform-bukkit-integration</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>cardinal-platform-bukkit-integration-cloud</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.avaje</groupId>
            <artifactId>avaje-inject</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.avaje</groupId>
            <artifactId>avaje-inject-generator</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-paper</artifactId>
        </dependency>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>