<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.witchvermillion.seed</groupId>
        <artifactId>seed-feature-participant</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>dev.witchvermillion.seed.participant</groupId>
    <artifactId>seed-feature-participant-api</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.github.elebras1</groupId>
            <artifactId>flecs-java</artifactId>
            <version>0.13.0</version>
        </dependency>

        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.1.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>