<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.witchvermillion.cardinal</groupId>
        <artifactId>cardinal-integration</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>cardinal-integration-redisson</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.avaje</groupId>
            <artifactId>avaje-inject</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>4.7.0</version>
        </dependency>
    </dependencies>

</project>